# Generated by Django 4.2.1 on 2023-05-28 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ClientName')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], max_length=10, verbose_name='ClubCard')),
                ('discount', models.IntegerField(choices=[(1, 10), (2, 20), (3, 30)])),
            ],
            options={
                'ordering': ['discount'],
            },
        ),
        migrations.CreateModel(
            name='ClubGym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('pool', 'SwimmingPool'), ('gym', 'Gym'), ('ring', 'BoxingRing'), ('tatami', 'Tatami')], max_length=20)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('swim', 'Swimming'), ('bobu', 'BoduBuilding'), ('yoga', 'Yoga'), ('karate', 'Karate'), ('sambo', 'Sambo'), ('judo', 'Judo'), ('box', 'Boxing')], max_length=50, verbose_name='SubjectName')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_price', models.IntegerField()),
                ('days', models.ManyToManyField(to='gym.day')),
                ('lesson_gym', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gym.clubgym', verbose_name='PlaceForConductingClasses')),
            ],
            options={
                'ordering': ['subject_name', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_count', models.IntegerField()),
                ('lessons', models.ManyToManyField(to='gym.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NoneMaster', max_length=50, unique=True, verbose_name='MasterName')),
                ('subject_name', models.CharField(choices=[('swim', 'Swimming'), ('bobu', 'BoduBuilding'), ('yoga', 'Yoga'), ('karate', 'Karate'), ('sambo', 'Sambo'), ('judo', 'Judo'), ('box', 'Boxing')], default='NoneSubject', max_length=20, verbose_name='SubjectName')),
                ('password', models.CharField(default='***', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='masters',
            field=models.ManyToManyField(to='gym.master'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='GroupName')),
                ('period_price', models.IntegerField()),
                ('clients', models.ManyToManyField(to='gym.client')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gym.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.clubcard', verbose_name='DiscountCard'),
        ),
    ]
