# Generated by Django 4.2.1 on 2023-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
