# Generated by Django 4.2.1 on 2023-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_master_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/photos/', verbose_name='Photo'),
        ),
    ]
