# Generated by Django 4.2.1 on 2023-05-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/lessons', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/masters', verbose_name='Photo'),
        ),
    ]
