# Generated by Django 4.2.1 on 2023-05-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_lesson_photo_alter_master_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubgym',
            old_name='type_name',
            new_name='name',
        ),
    ]
